version: '3.5'

services:
  accounts:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./accounts/src:/app/src
      - ./accounts/config:/app/config
      - ./accounts/.babelrc:/app/.babelrc
    environment:
      BLOCKCHAIN_HOST: http://ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - nightfall_network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - accounts
      - offchain
      - zkp
      - database
    volumes:
      - ./api-gateway/src:/app/src
      - ./api-gateway/config:/app/config
      - ./api-gateway/.babelrc:/app/.babelrc
    ports:
      - '8001:80'
    environment:
      ACCOUNTS_HOST: http://accounts
      ACCOUNTS_PORT: 80
      DATABASE_HOST: http://database
      DATABASE_PORT: 80
      OFFCHAIN_HOST: http://offchain
      OFFCHAIN_PORT: 80
      ZKP_HOST: http://zkp
      ZKP_PORT: 80
      RABBITMQ_HOST: amqp://rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - nightfall_network

  offchain:
    build:
      context: ./offchain
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
    volumes:
      - ./offchain/src:/app/src
      - ./offchain/build:/app/build
      - ./offchain/.babelrc:/app/.babelrc
      - ./offchain/__tests__:/app/__tests__
      - ./offchain/config:/app/config
    environment:
      AUTHENTICATION_API_HOST: http://api-gateway
      AUTHENTICATION_API_PORT: 80
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - nightfall_network

  zkp:
    build:
      context: ./zkp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache
      - merkle-tree
    volumes:
      # - ./zkp/.yalc:/app/.yalc
      - ./zkp/src:/app/src
      - ./zkp/build:/app/build
      - ./zkp/code:/app/code
      - ./zkp/.babelrc:/app/.babelrc
      - ./zkp/__tests__:/app/__tests__
      - ./zkp/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev:/dev # only for github actions
    environment:
      HASH_TYPE: 'sha' #override this with docker-compose.override.mimc
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      MERKLE_TREE_HOST: http://merkle-tree
      MERKLE_TREE_PORT: 80
      ZKP_CODE_VOLUME: nightfall_zkp-code-volume
      NIGHTLITE_LOG_LEVEL: debug
    networks:
      - nightfall_network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    volumes:
      - ./ui/src:/app/src
      - ./ui/angular.json:/app/angular.json
      - ./ui/tsconfig.json:/app/tsconfig.json
      - ./ui/tsconfig.base.json:/app/tsconfig.base.json
    ports:
      - '8000:80'
    environment:
      API_GATEWAY_HOST: http://localhost
      API_GATEWAY_PORT: 8001
      RABBITMQ_HOST: ws://localhost
      RABBITMQ_PORT: 15674
    networks:
      - nightfall_network

  ganache:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000
    ports:
      - '8545:8545'
    networks:
      - nightfall_network

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo-nightfall
    volumes:
      - ./database/src:/app/src
      - ./database/.babelrc:/app/.babelrc
      - ./database/config:/app/config
      - ./database/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js
    command: npm start
    environment:
      MONGO_HOST: mongo-nightfall
      MONGO_PORT: 27017
      MONGO_NAME: nightfall
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - nightfall_network

  mongo-nightfall:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nightfall
    volumes:
      - ./database/docker-entrypoint-initdb.d/01_setup_admin_user.js:/docker-entrypoint-initdb.d/01_setup_admin_user.js
      - ./database/is-mongo-ready.js:/is-mongo-ready.js
      - mongo-nightfall-volume:/data/db
    networks:
      - nightfall_network

  truffle-offchain:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./offchain/contracts:/truffle/contracts:delegated
      - ./offchain/migrations/:/truffle/migrations:delegated
      - ./offchain/build/contracts/:/truffle/build/contracts:cached
      - ./offchain/test/:/truffle/test:delegated
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m
    networks:
      - nightfall_network

  truffle-zkp:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./zkp/contracts/:/truffle/contracts:delegated
      - ./zkp/migrations/:/truffle/migrations:delegated
      - ./zkp/build/contracts/:/truffle/build/contracts:cached
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m
    networks:
      - nightfall_network

  truffle-nightlite:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./zkp/node_modules/@eyblockchain/nightlite/contracts/:/truffle/contracts:delegated
      - ./zkp/node_modules/@eyblockchain/nightlite/contracts/sha/MerkleTree.sol:/truffle/contracts/MerkleTree.sol:delegated
      - ./zkp/node_modules/@eyblockchain/nightlite/contracts/mimc/MiMC.sol:/truffle/contracts/MiMC.sol:delegated
      - ./zkp/node_modules/@eyblockchain/nightlite/migrations/:/truffle/migrations:delegated
      - ./zkp/build/contracts/:/truffle/build/contracts:cached
    depends_on:
      - ganache
    logging:
      options:
        max-size: 10m
    networks:
      - nightfall_network

  merkle-tree:
    image: eyblockchain/timber:v2.1.0
    restart: on-failure
    depends_on:
      - mongo-merkle-tree
      - ganache
    volumes:
      - ./config/merkle-tree:/app/config # mount point might be different if configuring from another application
      - ./zkp/contracts/:/app/contracts:consistent # required if deploying contracts from within this service (if CONTRACT_LOCATION = 'default')
      - ./zkp/build/:/app/build:consistent # required if CONTRACT_LOCATION = 'default'
      - app/node_modules
    ports:
      - '9000:80'
    environment:
      BLOCKCHAIN_HOST: ws://ganache
      BLOCKCHAIN_PORT: 8545
      CONTRACT_LOCATION: 'default' # Where to find the contractInstances?
      # Specify one of:
      # - 'remote' (to GET them from a remote microservice); or
      # - 'mongodb' (to get them from mongodb); or
      # - 'default' (to get them from the app/build/ folder)
      MONGO_HOST: mongodb://mongo-merkle-tree
      MONGO_PORT: 27017
      MONGO_NAME: merkle_tree
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    networks:
      - nightfall_network

  # The database storing the merkle tree
  mongo-merkle-tree:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=merkle_tree
    volumes:
      - ./database/docker-entrypoint-initdb.d/02_setup_admin_user.js:/docker-entrypoint-initdb.d/02_setup_admin_user.js
      - mongo-merkle-tree-volume:/data/db
    networks:
      - nightfall_network

  rabbitmq:
    image: rabbitmq
    volumes:
      - ./rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins
    ports:
      - '15674:15674'
    networks:
      - nightfall_network

volumes:
  mongo-nightfall-volume: {}
  mongo-merkle-tree-volume: {}
  zkp-code-volume:
    driver_opts:
      type: none
      device: $PWD/zkp/code/
      o: bind

networks:
  nightfall_network:
    name: nightfall_network
