#!/bin/bash
set -e

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

declare isTestFailed=false

printf "${GREEN}*** Cleaning up all test containers ***${NC}\n"
docker-compose down -v || true

printf "${GREEN}*** Pull zokrates docker image ***${NC}\n"
docker pull zokrates/zokrates:0.5.1

printf "${GREEN}*** docker-compose Build ***${NC}\n"
docker-compose build

printf "${GREEN}*** Install node modules dependencies of nightfall ***${NC}\n"
npm ci

printf "${GREEN}*** Installing zkp-util dependencies"
pushd zkp-utils
npm ci
popd

printf "${GREEN}*** Launching containerized ganache ***${NC}\n"
docker-compose up -d ganache

printf "${GREEN}*** Deploying all contracts ***${NC}\n"
docker-compose run --rm truffle-offchain migrate --reset --network=default
docker-compose run --rm truffle-zkp migrate --reset --network=default

printf "${GREEN}*** Launching containerized microservices ***${NC}\n"
if [[ -f ./zkp/code/gm17/ft-consolidation-transfer/proving.key && -f ./zkp/code/gm17/ft-consolidation-transfer/verification.key ]]
then
  docker-compose -f docker-compose.yml -f docker-compose.override.yml -f ./integration-test/docker-compose.test.yml up -d api-gateway
else
  docker-compose -f docker-compose.yml -f ./integration-test/docker-compose.test.yml up -d api-gateway
fi


# save all test logs to a file in background
printf "${GREEN}*** Saving the test logs to nightfall_test.log file ***${NC}\n"
docker-compose logs -f &> nightfall_test.log &disown

# delay needed to ensure all container are in running state.
sleep 40

# RUN test suits and remove test containers
printf "${GREEN}*** Run Integration test ***${NC}\n"
npm run test || isTestFailed=true

printf "${GREEN}*** List all containers with their Ips ***${NC}\n"
docker inspect -f '{{.Name}} {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker-compose ps -q)

printf "${GREEN}*** Cleaning up all containers ***${NC}\n"
docker-compose down -v || {
  # delay need as waiting time so all container are properly done
  # nightfall_default network have no dependency left.
  sleep 3

  printf "${GREEN}*** Remove nightfall network ***${NC}\n"
  docker network rm nightfall_network

  printf "${GREEN}*** Remove nightfall's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-nightfall-volume

  printf "${GREEN}*** Remove zkp-code volume ***${NC}\n"
  docker volume rm nightfall_zkp-code-volume

	printf "${GREEN}*** Remove the merkle tree's mongo volume ***${NC}\n"
  docker volume rm nightfall_mongo-merkle-tree-volume
}

printf  "${GREEN}*** Delete zkp and offchain contract's build folder ***${NC}\n"
rm -dr zkp/build/ || true
rm -dr offchain/build/ || true

if [[ -f ./zkp/code/gm17/ft-consolidation-transfer/proving.key && -f ./zkp/code/gm17/ft-consolidation-transfer/verification.key ]]
then
  printf "${GREEN}*** Remove empty zkp solidity file created from volume ***${NC}\n"
  rm zkp/contracts/MiMC.sol zkp/contracts/MerkleTree.sol || true
fi

if $isTestFailed
then
  printf "${RED}*** Integration test failed ***${NC}\n"
  exit 1
fi
